NetCoreApp2/Models/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NetCoreApp2.Models
{
    public class UsuarioViewModel
    {
        public Entities.Usuario eUsuario { get; set; }
        public List<Entities.Usuario> eListaUsuario { get; set; }

        public UsuarioViewModel() : base()
        {

        }
        
    }
}

NetCoreApp2/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NetCoreApp2.Models;
//using Microsoft.AspNet.OData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


using Utils; 
//using Microsoft.AspNet.OData.Query;

namespace Facturacion.Controllers
{
    //[Authorize]
    public class UsuarioController : Controller
    {
        

        [HttpGet]
        public IActionResult Listado()
        {
            UsuarioViewModel vUsuarioViewModel = new UsuarioViewModel();
            /* ------------------------------Cargada items para el menu ------------------- */
            vUsuarioViewModel.eListaUsuario = new Business.Usuario().GetListaUsuario();  

            return View(vUsuarioViewModel);
        }


        [HttpGet]
        public List<Entities.Usuario>  Listado2()
        {
            UsuarioViewModel vUsuarioViewModel = new UsuarioViewModel();
            /* ------------------------------Cargada items para el menu ------------------- */
            vUsuarioViewModel.eListaUsuario = new Business.Usuario().GetListaUsuario();

            return vUsuarioViewModel.eListaUsuario;
        }

        /// <summary>
        /// Odata para listado de contrato
        /// </summary>
        /// <param name="queryOptions"></param>
        /// <returns></returns>
       // [EnableQuery]
        //[HttpGet]
        //public ActionResult<List<ESE.Usuario>> Get(ODataQueryOptions<ESE.Usuario> queryOptions)
        //{
        //    try
        //    {
        //        UsuarioViewModel vUsuarioViewModel = new UsuarioViewModel(this.User);
        //        BSE.Usuario oUsuario = new BSE.Usuario();

        //        return Ok(oUsuario.GetListaUsuarios());

        //    }
        //    catch (Exception ex)
        //    {
        //        log.Error(ex);
        //        throw ex;
        //    }
        //}

        /* ********************************************* Return view Crear ************************************************** */
        [HttpGet]
        public IActionResult Crear(int Id)
        {
            try
            {
                UsuarioViewModel vUsuarioViewModel = new UsuarioViewModel();
                
                Business.Usuario oUsuario = new Business.Usuario();



                if (Id != 0)
                {
                    vUsuarioViewModel.eUsuario = oUsuario.GetUsuario(Id);
                }
                else {
                    vUsuarioViewModel.eUsuario = new Entities.Usuario();
                }

                return View(vUsuarioViewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        /// <summary>
        ///  Para la parte de carga de datos en base
        /// </summary>
        /// <param name="usuarioViewModel"></param>
        /// <returns></returns>
        /* ********************************************* Para inserar y editar ************************************************** */
        [HttpPost]
        public IActionResult Post(UsuarioViewModel vUsuarioViewModel)
        {
            try
            {
                Business.Usuario oUsuario = new Business.Usuario();

                if (vUsuarioViewModel.eUsuario.id_usuario != 0)
                {
                    oUsuario.Modificar(vUsuarioViewModel.eUsuario);
                }
                else
                {
                    oUsuario.Guardar(vUsuarioViewModel.eUsuario);
                }
            }
            catch (Exception ex)
            {

                return Ok(new { Result = false });
                throw ex;
            }
            return Ok(new { Result = true });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Business.Usuario oUsuario = new Business.Usuario();
            oUsuario.Eliminar(id);

            return Ok(new { Result = true });
        }
    }
}

NetCoreApp2/Views/Usuario/Crear.cshtml
@model NetCoreApp2.Models.UsuarioViewModel



<div class="content-wrapper">
    <div class="content">
        <form id="frmUsuario" class="form-horizontal" asp-controller="Usuario" asp-action="Post" autocomplete="off" data-ajax="true" data-ajax-method="POST"
              data-ajax-success="fnSuccess(data)" data-ajax-failure="fnFailure()">
            <div class="panel panel-default">
                <div class="panel-heading heading-primary">
                    <button class="btn btn-base cancelar" type="button" onclick="irAListado()">
                        <span class="fa span-button"></span>
                        <p class="text-button-secondary">VOLVER</p>
                    </button>
                    <button class="btn btn-base guardar" onclick="Guardar()">
                        <span class="fa span-button"></span>
                        <p class="text-button-primary">GUARDAR</p>
                    </button>
                </div>
                <div class="panel-body">
                    <section class="content">

                        <input type="hidden" id="id_empresa" asp-for="eUsuario.id_usuario" value="@Model.eUsuario.id_usuario" />

                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-lg-4 col-md-4">
                                <h4> <b style="color:red;">*</b>Nombre:</h4>
                                <div class="e-input-group">
                                    <input class="e-input" asp-for="eUsuario.nombre" type="text" value="@Model.eUsuario.nombre">
                                </div>
                                <span asp-validation-for="eUsuario.nombre" class="text-danger"></span>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-4 col-md-4">
                                <h4> <b style="color:red;">*</b>Correo:</h4>
                                <div class="e-input-group">
                                    <input class="e-input" asp-for="eUsuario.correo" type="email" value="@Model.eUsuario.correo">
                                </div>
                                <span asp-validation-for="eUsuario.correo" class="text-danger"></span>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-4 col-md-4">
                                <h4> <b style="color:red;">*</b>Nombre Usuario:</h4>
                                <div class="e-input-group">
                                    <input class="e-input" asp-for="eUsuario.user_name" type="text" value="@Model.eUsuario.user_name">
                                </div>
                                <span asp-validation-for="eUsuario.user_name" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-3 col-sm-3 col-lg-4 col-md-4">
                                <h4> Telefono:</h4>
                                <div class="e-input-group">
                                    <input class="e-input" asp-for="eUsuario.telefono" type="text" value="@Model.eUsuario.telefono">
                                </div>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-lg-4 col-md-4">
                                <h4> <b style="color:red;">*</b>Contraseña:</h4>
                                <div class="e-input-group">
                                    <input class="e-input" asp-for="eUsuario.contrasena" type="password" value="@Model.eUsuario.contrasena">
                                </div>
                                <span asp-validation-for="eUsuario.contrasena" class="text-danger"></span>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-lg-4 col-md-4">
                                <h4> Activo:</h4>
                            </div>
                        </div>

                    </section>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- ----------------------------------------- Eventos despues de llamar al metodo AJAX inicio ----------------- -->
<script>
    function fnSuccess(data) {
        console.log(data);
        if (data.result == true) {
            alert("Accione Correcta");
            irAListado();
        }
        else
            alert("Error en la accion");
    }

    function fnFailure() {
        alert("No existe");
    }
</script>
<!-- ----------------------------------------- Eventos despues de llamar al metodo AJAX inicio ----------------- -->
<script>
    function irAListado() {
        window.document.location.href = '@Url.Action("Listado", "Usuario")';
    }

    function Guardar() {
        //document.getElementById('stringListaSucursal').value = JSON.stringify(grid.dataSource);
    }
</script>

NetCoreApp2/Views/Usuario/Listado.cshtml
@{
    ViewData["Title"] = "Usuario Listado";
}

@model NetCoreApp2.Models.UsuarioViewModel;


<div class="content-wrapper">
    <div class="content">
        <div class="panel panel-default">
            <div class="panel-heading heading-primary">
                <button type="submit" class="btn btn-base crear" onclick="Crear()">
                    <span class="fa span-button"></span>
                    <p class="text-button-primary">Crear</p>
                </button>
            </div>
            <div class="panel-body">
                <section class="content">
                    <table>
                        <tr>
                            <th>id</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                        </tr>
                        @foreach (Entities.Usuario eUsuario in Model.eListaUsuario)
                        {
                        <tr>
                            <td> @eUsuario.id_usuario  </td>
                            <td> @eUsuario.nombre  </td>
                            <td>@eUsuario.telefono  </td>
                            <td>  <a href='@Url.Action("Crear","usuario", new { Id= eUsuario.id_usuario})'> text </a> </td>
                        </tr>
                        }
                    </table>
                </section>
                <!--  -------------------- PASO DE PARAMETRO POST ----------------- -->
                <form id="formPasoParametro" action='@Url.Action("Crear", "Usuario")' method="POST">
                    <input type="hidden" id="usuarioId" name="usuarioId" value="0">
                </form>
            </div>
        </div>
    </div>
</div>