NetCoreApp2/Models/ProyectoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NetCoreApp2.Models
{
    public class ProyectoViewModel
    {
        public Entities.Proyecto eProyecto { get; set; }
        public List<Entities.Proyecto> eListaProyecto { get; set; }

        public ProyectoViewModel() : base()
        {

        }

    }
}

NetCoreApp2/Controllers/ProyectoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NetCoreApp2.Models;
//using Microsoft.AspNet.OData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


using Utils;

namespace NetCoreApp2.Controllers
{
    public class ProyectoController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Listado()
        {
            ProyectoViewModel vProyectoViewModel = new ProyectoViewModel();
            /* ------------------------------Cargada items para el menu ------------------- */
            vProyectoViewModel.eListaProyecto = new Business.Proyecto().GetListaProyecto().ToList();

            return View(vProyectoViewModel);
        }


        [HttpGet]
        public List<Entities.Proyecto> Listado2()
        {
            ProyectoViewModel vProyectoViewModel = new ProyectoViewModel();
            /* ------------------------------Cargada items para el menu ------------------- */
            vProyectoViewModel.eListaProyecto = new Business.Proyecto().GetListaProyecto().ToList();

            return vProyectoViewModel.eListaProyecto;
        }

        /* ********************************************* Return view Crear ************************************************** */
        [HttpGet]
        public IActionResult Crear(int Id)
        {
            try
            {
                ProyectoViewModel vProyectoViewModel = new ProyectoViewModel();

                Business.Proyecto oProyecto = new Business.Proyecto();



                if (Id != 0)
                {
                    vProyectoViewModel.eProyecto = oProyecto.GetProyecto(Id);
                }
                else
                {
                    vProyectoViewModel.eProyecto = new Entities.Proyecto();
                }

                return View(vProyectoViewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        /* ********************************************* Para inserar y editar ************************************************** */
        [HttpPost]
        public IActionResult Post(ProyectoViewModel vProyectoViewModel)
        {
            try
            {
                Business.Proyecto oProyecto = new Business.Proyecto();

                if (vProyectoViewModel.eProyecto.UserId != 0)
                {
                    oProyecto.Modificar(vProyectoViewModel.eProyecto);
                }
                else
                {
                    oProyecto.Guardar(vProyectoViewModel.eProyecto);
                }
            }
            catch (Exception ex)
            {

                return Ok(new { Result = false });
                throw ex;
            }
            return Ok(new { Result = true });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Business.Proyecto oUsuario = new Business.Proyecto();
            oUsuario.Eliminar(id);

            return Ok(new { Result = true });
        }
    }
}

NetCoreApp2/Views/Proyecto/Crear.cshtml
@model NetCoreApp2.Models.ProyectoViewModel

<h4>ProyectoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NetCoreApp2/Views/Proyecto/Delete.cshtml
@model Entities.Proyecto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ProyectoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NetCoreApp2/Views/Proyecto/Details.cshtml
@model Entities.Proyecto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProyectoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProyectoId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProyectoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NetCoreApp2/Views/Proyecto/Edit.cshtml
@model Entities.Proyecto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProyectoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NetCoreApp2/Views/Proyecto/Index.cshtml
@model IEnumerable<Entities.Proyecto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Crear">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProyectoId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ProyectoId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProyectoId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

NetCoreApp2/Views/Proyecto/Listado.cshtml
@{
    ViewData["Title"] = "Proyecto Listado";
}

@model NetCoreApp2.Models.ProyectoViewModel;


<div class="content-wrapper">
    <div class="content">
        <div class="panel panel-default">
            <div class="panel-heading heading-primary">
                <button type="submit" class="btn btn-base crear" onclick="Crear()">
                    <span class="fa span-button"></span>
                    <p class="text-button-primary">Crear</p>
                </button>
            </div>
            <div class="panel-body">
                <section class="content">
                    <table>
                        <tr>
                            <th>id</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                        </tr>
                        @foreach (Entities.Proyecto eProyecto in Model.eListaProyecto)
                        {
                            <tr>
                                <td> @eProyecto.ProyectoId  </td>
                                <td> @eProyecto.Nombre  </td>
                                <td>@eProyecto.Descripcion  </td>
                                <td>  <a href='@Url.Action("Crear","Proyecto", new { Id= eProyecto.ProyectoId})'> text </a> </td>
                            </tr>
                        }
                    </table>
                </section>
                <!--  -------------------- PASO DE PARAMETRO POST ----------------- -->
                <form id="formPasoParametro" action='@Url.Action("Crear", "Proyecto")' method="POST">
                    <input type="hidden" id="usuarioId" name="usuarioId" value="0">
                </form>
            </div>
        </div>
    </div>
</div>